name: _purge

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-logs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_logs.yaml@27c2c51ec5c54f2dd40fc1f47fc63b12c30bc08a # v1.0.9
