name: _purge

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-logs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_logs.yaml@f3a66f8ee6c59613141f1499d9ae6060a025ffbb # v1.0.11
