name: _purge

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-logs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_logs.yaml@f25be9b95484bdb2a073065f78db5e3fe00184a6 # v1.0.12
