name: _purge_workflow_runs

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-workflow-runs:
    uses: ulfiac/commons/.github/workflows/reusable_purge_workflow_runs.yaml@964600790999f67b4c618f8114c277875eeeac53 # v1.0.29
