name: _terraform-docs
run-name: "terraform-docs: ${{ github.ref_name }}"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
      - '!terraform/modules/**/README.md'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: terraform-docs-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  terraform-docs:
    uses: ulfiac/commons/.github/workflows/reusable_terraform_docs.yaml@main
