name: _terraform-docs
run-name: "terraform-docs: ${{ github.ref_name }}"

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/modules/**'
      - '!terraform/modules/**/README.md'
  workflow_dispatch: {}

concurrency:
  group: terraform-docs-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-docs:
    uses: ulfiac/commons/.github/workflows/reusable_terraform_docs.yaml@e88e32a21a8bfa5c701de365c44fe9c37a8d42a8 # v1.0.6
