name: reusable deploy aws regions
run-name: "${{ inputs.terragrunt_action }}: aws, ${{ inputs.aws_account }}, ${{ inputs.aws_region }}, ${{ inputs.component }}"

on:
  workflow_call:
    inputs:
      annotate_context_details:
        default: false
        required: false
        type: boolean
      aws_account:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      component:
        required: true
        type: string
      terragrunt_action:
        required: true
        type: string
      terragrunt_parallelism:
        default: true
        required: false
        type: boolean
      terragrunt_strict_mode:
        default: true
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      annotate_context_details:
        default: false
        required: false
        type: boolean
      aws_account:
        default: mgmt
        options:
          - mgmt
        required: true
        type: choice
      aws_region:
        default: all
        options:
          - all
          - _global
          - ca-central-1
          - us-east-1
          - us-east-2
        required: true
        type: choice
      component:
        default: all
        required: true
        type: string
      terragrunt_action:
        default: plan
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice
      terragrunt_parallelism:
        default: true
        required: false
        type: boolean
      terragrunt_strict_mode:
        default: true
        required: false
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  deploy-aws-regions:
    name: ${{ matrix.aws_region }}
    strategy:
      matrix:
        aws_region: ${{ fromJson(inputs.aws_region == 'all' && '["_global","ca-central-1","us-east-1","us-east-2"]' || format('["{0}"]', inputs.aws_region)) }}
    uses: ./.github/workflows/reusable_terragrunt_action.yaml
    with:
      annotate_context_details: ${{ inputs.annotate_context_details }}
      aws_region: ${{ matrix.aws_region }}
      github_environment: aws_${{ inputs.aws_account }}
      terragrunt_action: ${{ inputs.terragrunt_action }}
      terragrunt_parallelism: ${{ inputs.terragrunt_parallelism }}
      terragrunt_queue_include_dir: ${{ inputs.component == 'all' && './**' || format('./{0}', inputs.component) }}
      terragrunt_strict_mode: ${{ inputs.terragrunt_strict_mode }}
      working_dir: "./aws/${{ inputs.aws_account }}/${{ matrix.aws_region }}"
    secrets: inherit
